#!/bin/bash
set -euo pipefail
cd "$(dirname "$0")"

# Log utility contents
for f in sbt-const sbt++field; do
  echo "::group::$f"
  f2="$(which "$f")"
  echo "> cat $f2"
  cat "$f2"
  echo
  echo "::endgroup::"
done

function test-sbt-const {
  echo "test-sbt-const $*"
  pushd "$1" >/dev/null
  result="$(sbt-const "$2")"
  if [ "$result" != "$3" ]; then
    echo "  Failed: [$result]"
    exit 2
  fi
  popd >/dev/null
}

test-sbt-const eg1 scala2 2.13.6
test-sbt-const eg1 scala3 3.0.2
